Repository CMPUT301F18T16/Baudit, pull requests merged in 2018-11, with the labels that each got.

#111 Refactored AndroidManifest.xml (Resolves #110)
  app/build.gradle
  app/src/androidTest/java/ca/klapstein/baudit/activities/SplashActivityTest.java
  app/src/main/AndroidManifest.xml
  app/src/main/java/ca/klapstein/baudit/activities/SplashActivity.java
  app/src/main/java/ca/klapstein/baudit/data/ContactInfo.java
  app/src/main/java/ca/klapstein/baudit/data/Email.java
  app/src/main/java/ca/klapstein/baudit/data/Password.java
  app/src/main/java/ca/klapstein/baudit/data/Problem.java
  app/src/main/java/ca/klapstein/baudit/data/Record.java
  app/src/main/java/ca/klapstein/baudit/data/Username.java
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: enhancement

#123 Added new storyboard PNG. +Reorganization (Resolves #114)
  doc/Baudit.png
  doc/StoryBoard.svg
  doc/mockup/Body Location Picker 1.png
  doc/mockup/Body Location Picker 2.png
  doc/mockup/Body Location Picker 3.png
  doc/mockup/Body Location Picker 4.png
  doc/mockup/Create Patient Account Frame.png
  doc/mockup/Create Provider Account Frame.png
  doc/mockup/Date Picker Frame.png
  doc/mockup/Delete Prompt Frame.png
  doc/mockup/Edit Patient Profile.png
  doc/mockup/Edit Problem Frame.png
  doc/mockup/Edit Provider Profile.png
  doc/mockup/Edit Record.png
  doc/mockup/Geolocation Select Frame.png
  doc/mockup/Geolocation View Frame.png
  doc/mockup/Patient Drawer.png
  doc/mockup/Patient Login Frame.png
  doc/mockup/Patient Search.png
  doc/mockup/Patient home screen.png
  doc/mockup/Photo Frame.png
  doc/mockup/Picture View Frame 1.png
  doc/mockup/Picture View Frame 2.png
  doc/mockup/Problems Map View.png
  doc/mockup/Provider Drawer.png
  doc/mockup/Provider Login Frame.png
  doc/mockup/Provider New Comment Record.png
  doc/mockup/Provider Search.png
  doc/mockup/Provider View Contact Info.png
  doc/mockup/Provider View Edited Problem.png
  doc/mockup/Provider View Patient Records.png
  doc/mockup/Provider View Problem.png
  doc/mockup/Provider home screen.png
  doc/mockup/Record with Body Location.png
  doc/mockup/Record with Location.png
  doc/mockup/Record with Photo.png
  doc/mockup/Slideshow 2.png
  doc/mockup/Slideshow.png
  doc/mockup/Time Picker Frame.png
  doc/mockup/View Record Frame.png
  doc/mockup/Welcome Splash Frame.png
  doc/storyboard/storyboard.fig
  doc/storyboard/storyboard.png
  doc/uml/UML.dia
Labels: documentation

#126 Feature/geo location tests
  app/src/main/java/ca/klapstein/baudit/activities/LogoutDialog.java
  app/src/main/java/ca/klapstein/baudit/data/GeoLocation.java
  app/src/test/java/ca/klapstein/baudit/data/GeoLocationTest.java
Labels: enhancement

#117 Sql framework
  app/build.gradle
  doc/baudit.db
  doc/databaseinit.sql
Labels: documentation

#132 adding updated UML
  doc/uml/baudit.uml
  doc/uml/baudit_uml.png
Labels: documentation

#131 adding phoneNumber tests
  app/src/test/java/ca/klapstein/baudit/data/PhoneNumberTest.java
Labels: enhancement

#137 attempting to speedup travis builds
  .travis.yml
  build.gradle
  scripts/travis_before_script.sh
  scripts/travis_create_avd.sh
  scripts/travis_script.sh
  scripts/travis_test_instrumentation.sh
  scripts/travis_test_unit.sh
Labels: enhancement

#136 adding unit test shims for presenters
  app/src/main/java/ca/klapstein/baudit/BauditDateFormat.java
  app/src/main/java/ca/klapstein/baudit/data/BodyPhoto.java
  app/src/main/java/ca/klapstein/baudit/data/BodyPhotoCoords.java
  app/src/main/java/ca/klapstein/baudit/data/Email.java
  app/src/main/java/ca/klapstein/baudit/data/Password.java
  app/src/main/java/ca/klapstein/baudit/data/Problem.java
  app/src/main/java/ca/klapstein/baudit/data/Record.java
  app/src/main/java/ca/klapstein/baudit/data/RecordPhoto.java
  app/src/main/java/ca/klapstein/baudit/presenters/BodyLocationPresenter.java
  app/src/main/java/ca/klapstein/baudit/presenters/LoginPresenter.java
  app/src/main/java/ca/klapstein/baudit/presenters/LogoutPresenter.java
  app/src/main/java/ca/klapstein/baudit/presenters/PhotoPresenter.java
  app/src/main/java/ca/klapstein/baudit/presenters/Presenter.java
  app/src/test/java/ca/klapstein/baudit/presenters/AddPhotoPresenterTest.java
  app/src/test/java/ca/klapstein/baudit/presenters/BodyLocationPresenterTest.java
  app/src/test/java/ca/klapstein/baudit/presenters/CreateAccountPresenterTest.java
  app/src/test/java/ca/klapstein/baudit/presenters/CreateCareProviderAccountPresenterTest.java
  app/src/test/java/ca/klapstein/baudit/presenters/CreatePatientAccountPresenterTest.java
  app/src/test/java/ca/klapstein/baudit/presenters/DeleteProblemPresenterTest.java
  app/src/test/java/ca/klapstein/baudit/presenters/DeleteRecordPresenterTest.java
  app/src/test/java/ca/klapstein/baudit/presenters/PatientListPresenterTest.java
  app/src/test/java/ca/klapstein/baudit/presenters/PhotoPresenterTest.java
  app/src/test/java/ca/klapstein/baudit/presenters/ViewAccountPresenterTest.java
Labels: enhancement

#125 Unit tests parameterized username
  app/src/test/java/ca/klapstein/baudit/data/UsernameTest.java
Labels: enhancement

#121 Implement Password Test
  app/src/main/java/ca/klapstein/baudit/data/Password.java
  app/src/main/java/ca/klapstein/baudit/managers/BauditRemoteManager.java
  app/src/test/java/ca/klapstein/baudit/data/PasswordTest.java
Labels: enhancement

#142 Feature/BodyPhoto
  app/build.gradle
  app/src/main/java/ca/klapstein/baudit/data/BodyPhoto.java
  app/src/test/java/ca/klapstein/baudit/data/BodyPhotoTest.java
Labels: enhancement

#141 Feature/RecordPhoto
  app/src/main/java/ca/klapstein/baudit/data/RecordPhoto.java
  app/src/test/java/ca/klapstein/baudit/data/RecordPhotoTest.java
Labels: enhancement

#145 WIP: Implementing basic MVP comms for login activities.
  app/src/androidTest/java/ca/klapstein/baudit/Activities/LoginCareProviderActivityTest.java
  app/src/androidTest/java/ca/klapstein/baudit/Activities/LoginPatientActivityTest.java
  app/src/androidTest/java/ca/klapstein/baudit/activities/LoginCareProviderActivityTest.java
  app/src/androidTest/java/ca/klapstein/baudit/activities/LoginPatientActivityTest.java
  app/src/main/AndroidManifest.xml
  app/src/main/java/ca/klapstein/baudit/activities/LoginCareProviderActivity.java
  app/src/main/java/ca/klapstein/baudit/activities/LoginPatientActivity.java
  app/src/main/java/ca/klapstein/baudit/activities/PatientListActivity.java
  app/src/main/java/ca/klapstein/baudit/activities/ProblemListActivity.java
  app/src/main/java/ca/klapstein/baudit/activities/SplashActivity.java
  app/src/main/java/ca/klapstein/baudit/models/RemoteModel.java
  app/src/main/java/ca/klapstein/baudit/presenters/LoginPresenter.java
  app/src/main/java/ca/klapstein/baudit/views/LoginView.java
  app/src/main/res/layout/activity_login_care_provider.xml
  app/src/main/res/layout/activity_login_patient.xml
  app/src/main/res/layout/activity_problem_list.xml
  app/src/main/res/layout/patient_login.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: enhancement

#118 Added problem Object to problem.java
  app/src/main/java/ca/klapstein/baudit/data/Problem.java
  app/src/test/java/ca/klapstein/baudit/data/ProblemTest.java
  app/src/test/java/ca/klapstein/baudit/data/ProblemTreeSetTest.java
Labels: documentation, enhancement

#158 ViewProblemActivity
  app/src/androidTest/java/ca/klapstein/baudit/activities/AddRecordActivityTest.java
  app/src/androidTest/java/ca/klapstein/baudit/activities/EditProblemActivityTest.java
  app/src/androidTest/java/ca/klapstein/baudit/activities/ViewProblemActivityTest.java
  app/src/main/AndroidManifest.xml
  app/src/main/java/ca/klapstein/baudit/activities/PatientHomeActivity.java
  app/src/main/java/ca/klapstein/baudit/activities/ViewProblemActivity.java
  app/src/main/java/ca/klapstein/baudit/fragments/DatePickerDialogFragment.java
  app/src/main/java/ca/klapstein/baudit/fragments/TimePickerDialogFragment.java
  app/src/main/java/ca/klapstein/baudit/presenters/ProblemPresenter.java
  app/src/main/java/ca/klapstein/baudit/presenters/ViewProblemPresenter.java
  app/src/main/java/ca/klapstein/baudit/views/ProblemView.java
  app/src/main/res/drawable-hdpi/ic_close_white_24dp.png
  app/src/main/res/drawable-hdpi/ic_content_save_white_24dp.png
  app/src/main/res/drawable-hdpi/ic_pencil_white_24dp.png
  app/src/main/res/drawable-mdpi/ic_close_white_24dp.png
  app/src/main/res/drawable-mdpi/ic_content_save_white_24dp.png
  app/src/main/res/drawable-mdpi/ic_pencil_white_24dp.png
  app/src/main/res/drawable-xhdpi/ic_close_white_24dp.png
  app/src/main/res/drawable-xhdpi/ic_content_save_white_24dp.png
  app/src/main/res/drawable-xhdpi/ic_pencil_white_24dp.png
  app/src/main/res/drawable-xxhdpi/ic_close_white_24dp.png
  app/src/main/res/drawable-xxhdpi/ic_content_save_white_24dp.png
  app/src/main/res/drawable-xxhdpi/ic_pencil_white_24dp.png
  app/src/main/res/drawable-xxxhdpi/ic_close_white_24dp.png
  app/src/main/res/drawable-xxxhdpi/ic_content_save_white_24dp.png
  app/src/main/res/drawable-xxxhdpi/ic_pencil_white_24dp.png
  app/src/main/res/drawable/close.xml
  app/src/main/res/drawable/content_save.xml
  app/src/main/res/drawable/pencil.xml
  app/src/main/res/layout/activity_problem.xml
  app/src/main/res/layout/activity_view_problem.xml
  app/src/main/res/layout/card_problem.xml
  app/src/main/res/layout/card_record.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/ca/klapstein/baudit/presenters/ViewProblemPresenterTest.java
  doc/uml/baudit.uml
Labels: enhancement

#161 Feature/unique id&login
  app/src/androidTest/java/ca/klapstein/baudit/activities/LoginCareProviderActivityTest.java
  app/src/androidTest/java/ca/klapstein/baudit/activities/LoginPatientActivityTest.java
  app/src/androidTest/java/ca/klapstein/baudit/models/DataModelTest.java
  app/src/androidTest/java/ca/klapstein/baudit/models/RemoteModelTest.java
  app/src/main/java/ca/klapstein/baudit/data/Account.java
  app/src/main/java/ca/klapstein/baudit/data/CareProvider.java
  app/src/main/java/ca/klapstein/baudit/data/Password.java
  app/src/main/java/ca/klapstein/baudit/data/Patient.java
  app/src/main/java/ca/klapstein/baudit/data/Problem.java
  app/src/main/java/ca/klapstein/baudit/data/Username.java
  app/src/main/java/ca/klapstein/baudit/models/DataModel.java
  app/src/main/java/ca/klapstein/baudit/models/RemoteModel.java
  app/src/main/java/ca/klapstein/baudit/presenters/CreateAccountPresenter.java
  app/src/main/java/ca/klapstein/baudit/presenters/LoginPresenter.java
  app/src/main/java/ca/klapstein/baudit/presenters/Presenter.java
  app/src/test/java/ca/klapstein/baudit/data/PasswordTest.java
  app/src/test/java/ca/klapstein/baudit/data/UsernameTest.java
Labels: enhancement

#157 added javadoc comments to most of the data models
  app/src/main/java/ca/klapstein/baudit/data/Account.java
  app/src/main/java/ca/klapstein/baudit/data/BodyPhoto.java
  app/src/main/java/ca/klapstein/baudit/data/BodyPhotoCoords.java
  app/src/main/java/ca/klapstein/baudit/data/ContactInfo.java
  app/src/main/java/ca/klapstein/baudit/data/Email.java
  app/src/main/java/ca/klapstein/baudit/data/Password.java
  app/src/main/java/ca/klapstein/baudit/data/PhoneNumber.java
  app/src/main/java/ca/klapstein/baudit/data/Problem.java
  app/src/main/java/ca/klapstein/baudit/data/Record.java
  app/src/main/java/ca/klapstein/baudit/data/RecordPhoto.java
  app/src/main/java/ca/klapstein/baudit/data/Username.java
Labels: documentation

#164 Feature/login pref
  app/src/androidTest/java/ca/klapstein/baudit/Activities/PatientHomeActivityTest.java
  app/src/androidTest/java/ca/klapstein/baudit/activities/EditAccountActivityTest.java
  app/src/androidTest/java/ca/klapstein/baudit/activities/LoginCareProviderActivityTest.java
  app/src/androidTest/java/ca/klapstein/baudit/activities/LoginPatientActivityTest.java
  app/src/androidTest/java/ca/klapstein/baudit/models/DataModelTest.java
  app/src/androidTest/java/ca/klapstein/baudit/models/PreferencesModelTest.java
  app/src/main/java/ca/klapstein/baudit/activities/LogoutDialog.java
  app/src/main/java/ca/klapstein/baudit/activities/PatientHomeActivity.java
  app/src/main/java/ca/klapstein/baudit/activities/PatientListActivity.java
  app/src/main/java/ca/klapstein/baudit/data/Email.java
  app/src/main/java/ca/klapstein/baudit/data/PhoneNumber.java
  app/src/main/java/ca/klapstein/baudit/models/DataModel.java
  app/src/main/java/ca/klapstein/baudit/models/PreferencesModel.java
  app/src/main/java/ca/klapstein/baudit/presenters/EditAccountPresenter.java
  app/src/main/java/ca/klapstein/baudit/presenters/LoginPresenter.java
  app/src/main/java/ca/klapstein/baudit/presenters/LogoutPresenter.java
  app/src/main/java/ca/klapstein/baudit/presenters/PatientHomePresenter.java
  app/src/main/java/ca/klapstein/baudit/presenters/PatientListPresenter.java
  app/src/test/java/ca/klapstein/baudit/data/EmailTest.java
  app/src/test/java/ca/klapstein/baudit/data/PhoneNumberTest.java
Labels: enhancement

#167 Feature/patient list activity drawer layout
  app/src/androidTest/java/ca/klapstein/baudit/Activities/PatientHomeActivityTest.java
  app/src/androidTest/java/ca/klapstein/baudit/activities/AddPhotoActivityTest.java
  app/src/androidTest/java/ca/klapstein/baudit/activities/CreateCareProviderActivityTest.java
  app/src/androidTest/java/ca/klapstein/baudit/activities/EditAccountActivityTest.java
  app/src/androidTest/java/ca/klapstein/baudit/activities/LocationActivityTest.java
  app/src/androidTest/java/ca/klapstein/baudit/activities/LoginCareProviderActivityTest.java
  app/src/androidTest/java/ca/klapstein/baudit/activities/LoginPatientActivityTest.java
  app/src/androidTest/java/ca/klapstein/baudit/activities/PatientListActivityTest.java
  app/src/androidTest/java/ca/klapstein/baudit/activities/ViewPhotoActivityTest.java
  app/src/androidTest/java/ca/klapstein/baudit/models/DataModelTest.java
  app/src/main/AndroidManifest.xml
  app/src/main/java/ca/klapstein/baudit/activities/LoginCareProviderActivity.java
  app/src/main/java/ca/klapstein/baudit/activities/LoginPatientActivity.java
  app/src/main/java/ca/klapstein/baudit/activities/PatientHomeActivity.java
  app/src/main/java/ca/klapstein/baudit/activities/PatientListActivity.java
  app/src/main/java/ca/klapstein/baudit/models/DataModel.java
  app/src/main/java/ca/klapstein/baudit/presenters/DrawerPresenter.java
  app/src/main/java/ca/klapstein/baudit/presenters/LoginPresenter.java
  app/src/main/java/ca/klapstein/baudit/views/DrawerView.java
  app/src/main/java/ca/klapstein/baudit/views/LoginView.java
  app/src/main/res/layout/activity_patient_home.xml
  app/src/main/res/layout/activity_patient_list.xml
  app/src/main/res/layout/drawer_header.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#169 Functional Logout
  app/src/androidTest/java/ca/klapstein/baudit/Activities/PatientHomeActivityTest.java
  app/src/androidTest/java/ca/klapstein/baudit/activities/CareProviderHomeActivityTest.java
  app/src/androidTest/java/ca/klapstein/baudit/activities/LoginCareProviderActivityTest.java
  app/src/main/AndroidManifest.xml
  app/src/main/java/ca/klapstein/baudit/activities/CareProviderHomeActivity.java
  app/src/main/java/ca/klapstein/baudit/activities/LoginCareProviderActivity.java
  app/src/main/java/ca/klapstein/baudit/activities/LoginPatientActivity.java
  app/src/main/java/ca/klapstein/baudit/activities/LogoutDialog.java
  app/src/main/java/ca/klapstein/baudit/activities/PatientHomeActivity.java
  app/src/main/java/ca/klapstein/baudit/presenters/CareProviderHomePresenter.java
  app/src/main/java/ca/klapstein/baudit/presenters/CreateAccountPresenter.java
  app/src/main/java/ca/klapstein/baudit/presenters/DrawerPresenter.java
  app/src/main/java/ca/klapstein/baudit/presenters/HomePresenter.java
  app/src/main/java/ca/klapstein/baudit/presenters/LogoutPresenter.java
  app/src/main/java/ca/klapstein/baudit/presenters/PatientHomePresenter.java
  app/src/main/java/ca/klapstein/baudit/views/DrawerView.java
  app/src/main/java/ca/klapstein/baudit/views/HomeView.java
  app/src/main/java/ca/klapstein/baudit/views/PatientListView.java
  app/src/main/java/ca/klapstein/baudit/views/ProblemListView.java
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/logout_dialog.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/test/java/ca/klapstein/baudit/presenters/CareProviderHomePresenterTest.java
  doc/uml/baudit.uml
Labels: enhancement

#171 Feature/add problem
  app/src/androidTest/java/ca/klapstein/baudit/activities/ProblemActivityTest.java
  app/src/androidTest/java/ca/klapstein/baudit/activities/RecordActivityTest.java
  app/src/main/java/ca/klapstein/baudit/activities/PatientHomeActivity.java
  app/src/main/java/ca/klapstein/baudit/activities/ProblemActivity.java
  app/src/main/java/ca/klapstein/baudit/activities/RecordActivity.java
  app/src/main/java/ca/klapstein/baudit/data/Problem.java
  app/src/main/java/ca/klapstein/baudit/models/DataModel.java
  app/src/main/java/ca/klapstein/baudit/presenters/CareProviderHomePresenter.java
  app/src/main/java/ca/klapstein/baudit/presenters/LoginPresenter.java
  app/src/main/java/ca/klapstein/baudit/presenters/PatientHomePresenter.java
  app/src/main/java/ca/klapstein/baudit/presenters/ProblemPresenter.java
  app/src/main/java/ca/klapstein/baudit/presenters/RecordPresenter.java
  app/src/main/java/ca/klapstein/baudit/views/ProblemView.java
  app/src/main/java/ca/klapstein/baudit/views/RecordView.java
  app/src/main/res/layout/activity_problem.xml
  app/src/main/res/layout/activity_record.xml
  app/src/main/res/values/strings.xml
  doc/uml/baudit.svg
  doc/uml/baudit.uml
  doc/uml/baudit_effective.svg
  doc/uml/baudit_effective.uml
Labels: enhancement

#173 WIP: Bugfix/test open map view
  app/src/androidTest/java/ca/klapstein/baudit/activities/LogoutDialogTest.java
  app/src/main/java/ca/klapstein/baudit/activities/PatientHomeActivity.java
  app/src/main/java/ca/klapstein/baudit/presenters/HomePresenter.java
  app/src/main/java/ca/klapstein/baudit/presenters/LoginPresenter.java
  app/src/main/java/ca/klapstein/baudit/presenters/PatientHomePresenter.java
Labels: bug

#174 Feature/refactoring
  app/build.gradle
  app/src/androidTest/java/ca/klapstein/baudit/Activities/LoginCareProviderActivityTestOffline.java
  app/src/androidTest/java/ca/klapstein/baudit/Activities/LoginPatientActivityTestOffline.java
  app/src/androidTest/java/ca/klapstein/baudit/Activities/PatientHomeActivityTest.java
  app/src/androidTest/java/ca/klapstein/baudit/activities/AddPhotoActivityTest.java
  app/src/androidTest/java/ca/klapstein/baudit/activities/CareProviderHomeActivityTest.java
  app/src/androidTest/java/ca/klapstein/baudit/activities/EditAccountActivityTest.java
  app/src/androidTest/java/ca/klapstein/baudit/activities/LocationActivityTest.java
  app/src/androidTest/java/ca/klapstein/baudit/activities/LoginCareProviderActivityTest.java
  app/src/androidTest/java/ca/klapstein/baudit/activities/LoginPatientActivityTest.java
  app/src/androidTest/java/ca/klapstein/baudit/activities/ProblemActivityTest.java
  app/src/androidTest/java/ca/klapstein/baudit/activities/RecordActivityTest.java
  app/src/androidTest/java/ca/klapstein/baudit/models/DataModelTest.java
  app/src/androidTest/java/ca/klapstein/baudit/models/PreferencesModelTest.java
  app/src/androidTest/java/ca/klapstein/baudit/models/RemoteModelTest.java
  app/src/main/java/ca/klapstein/baudit/activities/BodyLocationDialog.java
  app/src/main/java/ca/klapstein/baudit/activities/ViewAccountDialog.java
  app/src/main/java/ca/klapstein/baudit/models/DataModel.java
  app/src/main/java/ca/klapstein/baudit/models/PreferencesModel.java
  app/src/main/java/ca/klapstein/baudit/models/RemoteModel.java
  app/src/main/java/ca/klapstein/baudit/presenters/AddPhotoPresenter.java
  app/src/main/java/ca/klapstein/baudit/presenters/BodyLocationPresenter.java
  app/src/main/java/ca/klapstein/baudit/presenters/CareProviderHomePresenter.java
  app/src/main/java/ca/klapstein/baudit/presenters/CreateAccountPresenter.java
  app/src/main/java/ca/klapstein/baudit/presenters/CreateCareProviderAccountPresenter.java
  app/src/main/java/ca/klapstein/baudit/presenters/CreatePatientAccountPresenter.java
  app/src/main/java/ca/klapstein/baudit/presenters/DeleteProblemPresenter.java
  app/src/main/java/ca/klapstein/baudit/presenters/DeleteRecordPresenter.java
  app/src/main/java/ca/klapstein/baudit/presenters/EditAccountPresenter.java
  app/src/main/java/ca/klapstein/baudit/presenters/HomePresenter.java
  app/src/main/java/ca/klapstein/baudit/presenters/LocationPresenter.java
  app/src/main/java/ca/klapstein/baudit/presenters/LoginPresenter.java
  app/src/main/java/ca/klapstein/baudit/presenters/PatientHomePresenter.java
  app/src/main/java/ca/klapstein/baudit/presenters/PhotoPresenter.java
  app/src/main/java/ca/klapstein/baudit/presenters/ProblemPresenter.java
  app/src/main/java/ca/klapstein/baudit/presenters/ViewAccountPresenter.java
  app/src/main/java/ca/klapstein/baudit/views/ViewAccountView.java
  build.gradle
  doc/baudit.db
  doc/databaseinit.sql
Labels: enhancement

#184 removing logout button
  app/src/androidTest/java/ca/klapstein/baudit/activities/PatientHomeActivityTest.java
  app/src/main/java/ca/klapstein/baudit/activities/CareProviderHomeActivity.java
  app/src/main/java/ca/klapstein/baudit/activities/PatientHomeActivity.java
  app/src/main/java/ca/klapstein/baudit/presenters/HomePresenter.java
  app/src/main/java/ca/klapstein/baudit/presenters/StartPresenter.java
  app/src/main/res/menu/drawer_menu.xml
Labels: enhancement

#186 Feature/qr code account transfer
  app/build.gradle
  app/src/main/java/ca/klapstein/baudit/activities/StartActivity.java
  app/src/main/java/ca/klapstein/baudit/presenters/StartPresenter.java
  app/src/main/res/values/strings.xml
Labels: enhancement
