Repository CMPUT301F18T16/Baudit, pull requests merged in 2018-10, with the labels that each got.

#79 Create CODE_OF_CONDUCT.md CONTRIBUTORS.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  CONTRIBUTORS.md
Labels: documentation

#82 adding overview to `README.md`
  README.md
Labels: documentation

#91 Feature/CI Emulator
  .travis.yml
  README.md
  app/build.gradle
Labels: enhancement

#105 Resolves #93 Added validation checks for phone number object.
  app/src/main/java/ca/klapstein/baudit/Data/PhoneNumber.java
  app/src/test/java/ca/klapstein/baudit/Data/PhoneNumberTest.java
Labels: discussion, enhancement
